export const GLOBAL_COLORS = {
    WHITE: '#FFFFFF',
    MESSAGE_BACKGROUND_COLOR: '#618DFF',
    STATUS_BAR_COLOR: '#f8f8f8',
    CHAT_CARD_COLOR: '#EDF2FF',
};
export const MESSAGES_COLORS = {
    PERSONAL_MESSAGE_TEXT_COLOR: '#FFFFFF',
    PERSONAL_MESSAGE_BACKGROUND_COLOR: '#618DFF',
    FRIEND_MESSAGE_TEXT_COLOR: '#22304A',
    FRIEND_MESSAGE_BACKGROUND_COLOR: '#F5F5F5',
};
